#!/bin/bash

set -euo pipefail
# set -x

main() {
    versions=(
        "41"
        "42"
        "42-testing"
        "43"
        "43-updates"
        "43-testing"
        "Rawhide"
    )
    variants=(
        "Silverblue"
        "Kinoite"
        "Sericea"
        "Onyx"
        "COSMIC-Atomic"
    )
    arches=(
        "x86_64"
        "aarch64"
    )

    local date=""
    if [[ ${DATE+x} == "x" ]]; then
        date="${DATE}"
    else
        date="$(date "+%Y%m%d")"
    fi
    local -r summary="$(ostree remote summary fedora)"

    local -r red="\e[31m"
    local -r blue="\e[34m"
    local -r end="\e[0m"

    for variant in "${variants[@]}"; do
        (
        printf "%-13s" "${variant}"
        for r in "${versions[@]}"; do
            echo -n "|$r"
        done
        echo ""

        for arch in "${arches[@]}"; do
            if [[ "${variant}" == "Onyx" && "${arch}" != "x86_64" ]]; then
                continue
            fi
            buf=""
            for rel in "${versions[@]}"; do
                release=${rel%%-*}
                branch=${rel##*-}
                if [[ -n "${branch}" ]] && [[ "${branch}" != "${release}" ]]; then
                    branch="/${branch}"
                else
                    branch=""
                fi
                version="$(echo "${summary}" \
                        | grep -E "${release,,}/${arch}${branch}/${variant,,}$" -A3 --no-group-separator \
                        | grep "Version" \
                        | awk 'NF>1{print $NF}')" \
                        || version=""

                mainver="${version%.*}"
                if [[ "${mainver}" != "${release}.${date}" ]] && [[ "${mainver}" != "${release}.${date}.n" ]]; then
                    buf+="$(printf "|${red}%-15s${end}" "${version}")"
                else
                    buf+="$(printf "|${blue}%-15s${end}" "${version}")"
                fi
            done
            if [[ "$(echo "${buf}" | tr -d ' ')" != "||||" ]]; then
                echo "${arch}${buf}"
            fi
        done
        ) | column -t -s "|"
        echo ""
    done
}

main "${@}"
