#!/usr/bin/env bash

set -u -o pipefail
# Do not exit if one command failed
# set -e
# set -x

update_container_images() {
	echo "[+] Updating container images..."
	# docker.io/digitalocean/doctl:latest
	# quay.io/coreos-assembler/coreos-assembler:rhcos-4.6
	# quay.io/coreos-assembler/coreos-assembler:rhcos-4.7
	# quay.io/coreos-assembler/coreos-assembler:rhcos-4.8
	# quay.io/coreos-assembler/coreos-assembler:rhcos-4.9
	# quay.io/coreos/ignition-validate:release
	# registry.access.redhat.com/ubi8/ubi:8.4
	# registry.access.redhat.com/ubi8/ubi:latest
	# registry.fedoraproject.org/fedora:34
	# registry.fedoraproject.org/fedora:35
	images=(
		'registry.fedoraproject.org/fedora:latest'
		'quay.io/coreos/butane:release'
		'quay.io/coreos/coreos-installer:release'
		'docker.io/antora/antora:latest'
		'quay.io/coreos-assembler/coreos-assembler:latest'
	)
	for img in "${images[@]}"; do
		podman pull "${img}"
	done
	for img in $(podman images --filter dangling=true --format "{{.ID}}"); do
		podman rmi "${img}"
	done
	echo "[+] Done"
}

update_firmwares() {
	echo "[+] Updating firmwares..."
	sudo fwupdmgr refresh
	sudo fwupdmgr update
	echo "[+] Done"
}

main() {
	(
		source /etc/os-release;
		if [[ "${VARIANT_ID}" == "container" ]]; then
			echo "You should run this script outside of a container";
			exit 1;
		fi
	) || exit 1

	local SYSTEM=false
	if [[ "${#}" -gt 0 ]]; then
		case "${1}" in
			"s"|"sy"|"sys"|"syst"|"syste"|"system")
				SYSTEM=true
				;;
		esac
		case "${1}" in
			"c"|"co"|"con"|"cont"|"conta"|"contai"|"contain"|"containe"|"container")
				update_container_images
				exit 0
				;;
		esac
		case "${1}" in
			"f"|"fi"|"fir"|"firm"|"firmw"|"firmwa"|"firmwar"|"firmware")
				update_firmwares
				exit 0
				;;
		esac
	fi

	local OSTREE=false
	if [[ -f "/run/ostree-booted" ]]; then
		OSTREE=true
	fi

	if [[ "${SYSTEM}" == true ]] && [[ "${OSTREE}" == false ]] && [[ -z "${TMUX+x}" ]]; then
		tmux attach-session -t update || tmux new-session -s update -- ~/.local/bin/+update system
		exit 0
	fi

	if [[ "${SYSTEM}" == true ]]; then
		if [[ "${OSTREE}" == true ]]; then
			echo "[+] Updating system (rpm-ostree)..."
			rpm-ostree update
		else
			echo "[+] Updating system (dnf)..."
			sudo dnf update --refresh
		fi
	fi

	echo "[+] Updating system Flatpaks..."
	flatpak --system update --assumeyes
	flatpak --system remove --unused --assumeyes

	echo "[+] Updating toolboxes..."
	# 'quay.io/travier/toolbox-kdedev:latest'
	# 'quay.io/travier/toolbox-texlive:latest'
	images=(
		'quay.io/travier/toolbox:latest'
	)
	for img in "${images[@]}"; do
		podman pull "${img}"
		local name="${img%:*}"
		name="${name##*/}"
		toolbox rm --force "${name}"
		toolbox create --image "${img}" "${name}"
	done

	echo "[+] Updating Rust crates..."
	rustup update
	toolbox run --container 'toolbox' ~/.cargo/bin/cargo install-update -a
	toolbox run --container 'toolbox' ~/.cargo/bin/cargo cache -a

	echo "[+] Done"
	if [[ -n "${TMUX+x}" ]]; then
		exec "${SHELL}"
	fi
}

main "${@}"
