#!/usr/bin/env bash

set -u -o pipefail
# set -e # Do not exit if one command failed
# set -x # Only for debugging

update_container_images() {
    echo "[+] Updating container images..."
    # registry.access.redhat.com/ubi8/ubi:8.6
    # registry.access.redhat.com/ubi8/ubi:latest
    # registry.fedoraproject.org/fedora:36
    images=(
        'registry.fedoraproject.org/fedora:latest'
        'docker.io/antora/antora:latest'
        'quay.io/coreos-assembler/coreos-assembler:latest'
    )
    for img in "${images[@]}"; do
        podman pull "${img}"
    done
    for img in $(podman images --filter dangling=true --format "{{.ID}}"); do
        podman rmi "${img}"
    done
    echo "[+] Done"
}

update_firmwares() {
    echo "[+] Updating firmwares..."
    sudo fwupdmgr refresh
    sudo fwupdmgr update
    echo "[+] Done"
}

update_toolboxes() {
    echo "[+] Updating toolboxes..."
    # Only update toolbox images currently in use
    for img in $(podman images -n --format "{{.Repository}}" | grep "quay.io/travier/toolbox"); do
        podman pull "${img}"
        local name="${img%:*}"
        name="${name##*/}"
        toolbox rm --force "${name}" || true
        toolbox create --image "${img}" "${name}"
    done
    for img in $(podman images --filter dangling=true --format "{{.ID}}"); do
        podman rmi "${img}"
    done

    echo "[+] Updating rootful toolboxes..."
    if [[ -f "/run/.containerenv" ]]; then
        echo "[+] Can not (yet) update rootful toolboxes from a rootless container."
        return
    fi
    # Only update toolbox images currently in use
    # TODO: Force quay.io/travier/toolbox-root
    for img in $(sudo podman images -n --format "{{.Repository}}" | grep "quay.io/travier/toolbox"); do
        sudo podman pull "${img}"
        local name="${img%:*}"
        name="${name##*/}"
        sudo toolbox rm --force "${name}" || true
        sudo toolbox create --image "${img}" "${name}"
    done
    for img in $(sudo podman images --filter dangling=true --format "{{.ID}}"); do
        sudo podman rmi "${img}"
    done
}

main() {
    local SYSTEM=false
    if [[ "${#}" -gt 0 ]]; then
        case "${1}" in
            "s"|"sys"|"system")
                SYSTEM=true
                ;;
        esac
        case "${1}" in
            "c"|"cont"|"container")
                update_container_images
                exit 0
                ;;
        esac
        case "${1}" in
            "f"|"firm"|"firmware")
                update_firmwares
                exit 0
                ;;
        esac
        case "${1}" in
            "t"|"tb"|"tbx"|"toolbox")
                update_toolboxes
                exit 0
                ;;
        esac
    fi

    if [[ "${SYSTEM}" == true ]]; then
        echo "[+] Updating system (rpm-ostree)..."
        rpm-ostree update

        echo "[+] Updating system Flatpaks..."
        flatpak --system update --assumeyes
        flatpak --system remove --unused --assumeyes
    fi

    # Use a fixed toolbox to avoid issues during a Fedora major version rebase
    local -r toolbox="toolbox"

    echo "[+] Updating main toolbox..."
    toolbox run --container "${toolbox}" sudo dnf update -y

    echo "[+] Updating Rust crates..."
    rustup update
    toolbox run --container "${toolbox}" ~/.cargo/bin/cargo install-update -a
    # toolbox run --container "${toolbox}" ~/.cargo/bin/cargo cache -a

    echo "[+] Done"
}

main "${@}"
